#!/bin/bash

DRY_RUN=0
function printHelp {
  echo "Utility to run games and applications in separate X on discrete Nvidia graphic card"
  echo "Usage: "
  echo "nvidia-xrun [<options>] [<app>]"
  echo "Options: "
  echo "  -d    Dry run - prints the final command but does not execute it"
}

function execute {
  if [[ ${DRY_RUN} -eq 1 ]]
    then
    echo ">>Dry run. Command: $*"
  else
    eval $*
  fi
}

if [[ "$1" == "-d" ]]
  then
    DRY_RUN=1
    shift 1
fi

# load config file
. /etc/default/nvidia-xrun

if [[ $EUID -eq 0 ]]; then
   echo "This script must not be run as root" >&2
   exit 1
fi

# calculate current VT
LVT=`fgconsole`

# calculate first usable display
XNUM="-1"
SOCK="something"
while [[ ! -z "$SOCK" ]]
do
  XNUM=$(( $XNUM + 1 ))
  SOCK=$(ls -A -1 /tmp/.X11-unix | grep "X$XNUM" )
done

NEWDISP=":$XNUM"

if [[ ! -z "$*" ]] # generate exec line if arguments are given
then
  # test if executable exists in path
  if [[ -x "$(which $1 2> /dev/null)" ]]
  then
    # generate exec line
    EXECL="$(which $1)"
  # test if executable exists on disk
  elif [[ -e "$(realpath "$1")" ]]
  then
    # generate exec line
    EXECL="$(realpath "$1")"
  else
    echo "$1: No such executable!"
    exit 1
  fi
  shift 1
  EXECL="$EXECL $*"
else # prepare to start new X sessions if no arguments passed
  EXECL=""
fi

EXECL="/etc/X11/xinit/nvidia-xinitrc \"$EXECL\""

COMMAND="xinit $EXECL -- $NEWDISP vt$LVT -nolisten tcp -br -config xorg.nvidia-xrun.conf -configdir xorg.nvidia-xrun.conf.d"

# --------- TURNING ON GPU -----------
if [[ "$ENABLE_PM" == '1' ]]; then
  sudo /usr/lib/nvidia-xrun/nv-card-controller xrun on
elif [[ "$ENABLE_PM" == '2' ]]; then
  sudo /usr/lib/nvidia-xrun/nv-card-controller bumblebee on
fi

# ---------- LOADING MODULES ----------
sudo /usr/lib/nvidia-xrun/nv-modules load

# ---------- EXECUTING COMMAND --------
export NVRUN_NVIDIA_SESSION=1
execute ${COMMAND}
sleep 3
unset NVRUN_NVIDIA_SESSION

# ---------- UNLOADING MODULES --------
sudo /usr/lib/nvidia-xrun/nv-modules unload

# --------- TURNING OFF GPU ----------
if [[ "$ENABLE_PM" == '1' ]]; then
  sudo /usr/lib/nvidia-xrun/nv-card-controller xrun off
elif [[ "$ENABLE_PM" == '2' ]]; then
  sudo /usr/lib/nvidia-xrun/nv-card-controller bumblebee off
fi

# ---------- CHECK MODULES ----------
if [[ -z "`lsmod | grep nvidia`" ]]; then
  echo "Modules unloaded correctly"
else
  echo Still module\(s\) loaded: `lsmod | grep nvidia | awk '{printf $1" "}'`
fi
