#!/bin/bash

function usage() {
  echo "Usage:"
  echo -e "\t $0 [load|unload]"
}

function execute() {
  eval $*
}

function load() {
  for module in "${MODULES_LOAD[@]}"
  do
    echo "Loading module ${module}"
    execute "modprobe ${module}"
  done
}

function unload() {
  # need to stop the nvidia-persistenced service in order to make the card go back to sleep
  test "active" = "`systemctl status nvidia-persistenced.service | grep Active | awk '{printf $2}'`" && \
  systemctl stop nvidia-persistenced && \
  sleep 3

  for module in "${MODULES_UNLOAD[@]}"
  do
    echo "Unloading module ${module}"
    execute "modprobe -r ${module}"
  done
}

. /etc/default/nvidia-xrun

if [[ -z "$1" ]]; then
  usage
  exit 1
else
  case "$1" in
    "load") load;;
    "unload") unload;;
    *) usage; exit 1;;
  esac
fi
